global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'marzban'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['marzban:8000']

  - job_name: 'node-exporter'
    file_sd_configs:
      - files:
        - '/etc/prometheus/nodes/*.json'
        refresh_interval: 1m

  - job_name: 'caddy'
    static_configs:
      - targets: ['caddy:2019']
